default:
  interruptible: true
  image: eclipse-temurin:21-jdk-alpine

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: $CI_COMMIT_TAG

stages:
  - build
  - test
#  - deploy
#  - destroy

build_statistics:
  stage: build
  script:
    - echo "Building statistics project"
    - chmod +x gradlew
    - cd ./statistics
    - ../gradlew bootJar
    - cd ..
  artifacts:
    name: "build-statistics-artifact"
    when: on_success
    expire_in: 2 days
    paths:
      - "statistics/build/libs/*.jar"

test_statistics:
  stage: test
  needs: []
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind

  before_script:
    - apk add --no-cache docker
    - docker info

  script:
    - echo "Running statistics tests"
    - chmod +x gradlew
    - cd ./statistics
    - ../gradlew test
    - cd ..

  artifacts:
    when: always
    reports:
      junit: "statistics/build/test-results/test/**/TEST-*.xml"
