default:
  interruptible: true
  image: eclipse-temurin:21-jdk-alpine

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: $CI_COMMIT_TAG

stages:
  - build
  - test
  - deploy
  - destroy


# -- reusable configurations --

# build

.build-job-template: &build-job-template
  script:
    - echo "Building $CONTEXT_NAME project"
    - chmod +x gradlew
    - cd ./$CONTEXT_NAME
    - ../gradlew clean bootBuildImage --stacktrace
    - cd ..
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == 'ci-cd' || $CI_COMMIT_BRANCH == 'prod'

# test

.test-job-template: &test_job_template
  script:
    - echo "Running $CONTEXT_NAME tests"
    - chmod +x gradlew
    - cd ./$CONTEXT_NAME
    - ../gradlew test
    - cd ..
  artifacts:
    when: always
    reports:
      junit: "$CONTEXT_NAME/build/test-results/test/**/TEST-*.xml"


# ----------------------- BUILD ----------------------- #

#build_chatbot:
#  stage: build
#  variables:
#    CONTEXT_NAME: chatbot
#  script: *build_script
#  rules: *build_rules
#
#build_gameplay:
#  stage: build
#  variables:
#    CONTEXT_NAME: gameplay
#  script: *build_script
#  rules: *build_rules
#
#build_game_registry:
#  stage: build
#  variables:
#    CONTEXT_NAME: gameRegistry
#  script: *build_script
#  rules: *build_rules
#
#build_player:
#  stage: build
#  variables:
#    CONTEXT_NAME: player
#  script: *build_script
#  rules: *build_rules

build_statistics:
  <<: *build-job-template
  stage: build
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    CONTEXT_NAME: statistics
  services:
    - docker:dind


#build_storefront:
#  stage: build
#  variables:
#    CONTEXT_NAME: storefront
#  script: *build_script
#  rules: *build_rules

# ----------------------- TEST ----------------------- #

#test_chatbot:
#  stage: test
#  needs: []
#  variables:
#    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""
#    CONTEXT_NAME: chatbot
#  services:
#    - docker:dind
#  before_script:
#    - apk add --no-cache docker
#  script: *test_script
#  artifacts: *test_artifacts
#
#test_gameplay:
#  stage: test
#  needs: []
#  variables:
#    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""
#    CONTEXT_NAME: gameplay
#  services:
#    - docker:dind
#  before_script:
#    - apk add --no-cache docker
#  script: *test_script
#  artifacts: *test_artifacts
#
#test_game_registry:
#  stage: test
#  needs: []
#  variables:
#    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""
#    CONTEXT_NAME: gameRegistry
#  services:
#    - docker:dind
#  before_script:
#    - apk add --no-cache docker
#  script: *test_script
#  artifacts: *test_artifacts
#
#test_player:
#  stage: test
#  needs: []
#  variables:
#    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""
#    CONTEXT_NAME: player
#  services:
#    - docker:dind
#  before_script:
#    - apk add --no-cache docker
#  script: *test_script
#  artifacts: *test_artifacts

test_statistics:
  <<: *test_job_template
  stage: test
  needs: []
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    CONTEXT_NAME: statistics
  services:
    - docker:dind
  before_script:
    - apk add --no-cache docker

#test_storefront:
#  stage: test
#  needs: []
#  variables:
#    DOCKER_HOST: "tcp://docker:2375"
#    DOCKER_TLS_CERTDIR: ""
#    CONTEXT_NAME: storefront
#  services:
#    - docker:dind
#  before_script:
#    - apk add --no-cache docker
#  script: *test_script
#  artifacts: *test_artifacts

# ----------------------- SAST ----------------------- #

sast:
  stage: test
  needs: []
  variables:
    SAST_EXCLUDED_PATHS: src/test
    SEARCH_MAX_DEPTH: '10'
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

semgrep-sast:
  rules:
    - if: $SAST_DISABLED == 'true' || $SAST_DISABLED == '1'
      when: never
    - if: $SAST_EXCLUDED_ANALYZERS =~ /semgrep/
      when: never
    - if: $CI_COMMIT_BRANCH || $CI_PIPELINE_SOURCE == "merge_request_event"
      exists:
        - '**/*.java'

# ----------------------- DEPLOY ----------------------- #

# DEV

deploy_postgres_dev:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  when: on_success
  needs:
    # In here add all other build stages when setup
    - build_statistics
  before_script:
    - tdnf install -y postgresql
    - psql --version
    - az login --service-principal -u $DEV_AZURE_APP_ID -p $DEV_AZURE_PASSWORD --tenant $DEV_AZURE_TENANT
  script:
    - chmod +x cicd/deploy-database-vnet.sh
    - cicd/deploy-database-vnet.sh
  # This will only run when you commit to a merge request or to the ci-cd branch
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'ci-cd'


deploy_statistics_dev:
  image: mcr.microsoft.com/azure-cli
  stage: deploy
  when: on_success
  needs:
    - deploy_postgres_dev
    - build_statistics
  before_script:
    - az login --service-principal -u $DEV_AZURE_APP_ID -p $DEV_AZURE_PASSWORD --tenant $DEV_AZURE_TENANT
    - az extension add --name containerapp --upgrade
  script:
    - tag=$CI_COMMIT_REF_NAME
    - chmod +x cicd/deploy-statistics-dev.sh
    - cicd/deploy-statistics-dev.sh
  environment:
    name: statistics-dev
    deployment_tier: testing
    action: start
    auto_stop_in: 1 hours
    on_stop: destroy_statistics_dev
  # This will only run when you commit to a merge request or to the ci-cd branch
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'ci-cd'

# PROD

#deploy_statistics_prod:
#  stage: deploy
#  when: manual
#  needs:
#    - build_statistics
#  script:
#    -
#  # This will only be available if you perform a tag, or you commit to main
#  rules:
#    - if: $CI_COMMIT_TAG
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


# ----------------------- DESTROY ----------------------- #

# DEV

destroy_statistics_dev:
  image: mcr.microsoft.com/azure-cli
  stage: destroy
  when: manual
  before_script:
    - az login --service-principal -u $DEV_AZURE_APP_ID -p $DEV_AZURE_PASSWORD --tenant $DEV_AZURE_TENANT
    - az extension add --name containerapp --upgrade
  script:
    - CONTAINER_NAME="statistics-dev-container"
    - RESOURCE_GROUP="rg_bandit_games_dev"
    - echo "Deleting container app"
    - az containerapp delete --name $CONTAINER_NAME --resource-group $RESOURCE_GROUP --yes
  environment:
    name: statistics-dev
    action: stop
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'ci-cd'

