#### Get access token with player user

POST http://localhost:8180/realms/bandit-realm/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=bandit-backend&client_secret=**********&username=deanplayer@kdg.be&password=password&grant_type=password&scope=openid

//saving the warehouse access token
> {%client.global.set("logged-in-user", response.body.access_token);%}

### get all games (only title and Icon)

GET http://localhost:8092/game-registry/games
Accept: application/json
Authorization: Bearer {{logged-in-user}}


### get all games with icon

GET http://localhost:8092/game-registry/games/overview
Accept: application/json

### get all games with icon by title like ch

GET http://localhost:8092/game-registry/games/overview?title=che
Accept: application/json

### get all games with icon by title like che and price below 100 (1 record)

GET http://localhost:8092/game-registry/games/overview?title=che&maxPrice=100.0
Accept: application/json

### get all games with icon by title like che and price below 100 (empty)

GET http://localhost:8092/game-registry/games/overview?title=che&maxPrice=5.0
Accept: application/json

### get all games with icon by title like che and price below 100 (empty)

GET http://localhost:8092/game-registry/games/overview?title=&maxPrice=5.0
Accept: application/json
