#### Get access token with player user

POST http://localhost:8180/realms/bandit-realm/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=bandit-backend&client_secret=**********&username=john@gmail.com&password=johnnyboy&grant_type=password&scope=openid

> {%client.global.set("logged-in-user", response.body.access_token);%}

### Search player
GET http://localhost:8090/api/player?username=Pla
Accept: application/json
Authorization: Bearer {{logged-in-user}}


### Get all player friends
GET http://localhost:8090/api/player/friends
Accept: application/json
Authorization: Bearer {{logged-in-user}}