server:
  port: ${PORT:8091}
  servlet:
    context-path: /chatbot


spring:
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_PROD:create-drop}
      show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5555/bandit_db}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASS:password}
  rabbitmq:
    host: ${RABBIT_URL:localhost}
    port: 5672
    username: ${RABBITMQ_USER:myuser}
    password: ${RABBITMQ_PASSWORD:mypassword}
    virtual-host: ${RABBITMQ_VHOST:/}
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak.victoriousocean-73fa80ad.northeurope.azurecontainerapps.io/realms/bandit-realm
          jwk-set-uri: https://keycloak.victoriousocean-73fa80ad.northeurope.azurecontainerapps.io/realms/bandit-realm/protocol/openid-connect/certs

python:
  url: ${PYTHON_URL:http://localhost:8000}
