#### Get access token with admin user

POST http://localhost:8180/realms/bandit-realm/protocol/openid-connect/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id=bandit-backend&client_secret=**********&username=deanadmin@kdg.be&password=password&grant_type=password&scope=openid

> {%client.global.set("logged-in-admin", response.body.access_token);%}

### export completedSessions for a game to CSV

GET http://localhost:8095/statistics/export/statistics/games/d77e1d1f-6b46-4c89-9290-3b9cf8a7c001/sessions
Accept: text/csv
Authorization: Bearer {{logged-in-admin}}

### export achievementProgress for a game to CSV

GET http://localhost:8095/statistics/export/statistics/games/d77e1d1f-6b46-4c89-9290-3b9cf8a7c001/achievements
Accept: text/csv
Authorization: Bearer {{logged-in-admin}}