server:
  port: ${PORT:8094}
  servlet:
    context-path: /player


spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bandit-realm
          jwk-set-uri: http://localhost:8180/realms/bandit-realm/protocol/openid-connect/certs
