spring:
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true


stripe:
  apiKey: stripe_key