  services:
    postgres_app_db:
      image: postgres:16.1-alpine
      restart: no
      environment:
        POSTGRES_DB: 'bandit_db'
        POSTGRES_USER: 'user'
        POSTGRES_PASSWORD: 'password'
        POSTGRES_ROOT_PASSWORD: 'password'
      ports:
        - '5555:5432'
      networks:
        - backend
      volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/db.sql
        - ./postgresql/data:/var/lib/postgresql

    app_rabbitmq:
      image: rabbitmq:3.13.7-management-alpine
      environment:
        - RABBITMQ_DEFAULT_USER=myuser
        - RABBITMQ_DEFAULT_PASS=mypassword
      ports:
        - "5672:5672" #AMQP
        - "15672:15672" #MGMT
      networks:
        - backend
      volumes:
        - ./rabbitmq/data/:/var/lib/rabbitmq/
        - ./rabbitmq/log/:/var/log/rabbitmq/



    idp_mysql:
      image: mysql:9.0.1
      volumes:
        - ./idp_mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
      ports:
        - '3307:3306'
      networks:
        - kc

    idp_keycloak:
      image: quay.io/keycloak/keycloak:25.0.5
      environment:
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_DB=mysql
        - KC_DB_URL_HOST=idp_mysql
        - KC_DB_URL_DATABASE=keycloak
        - KC_DB_USERNAME=keycloak
        - KC_DB_PASSWORD=password
        - KC_FEATURES=token-exchange,admin-fine-grained-authz
      command: start-dev
      ports:
        - "8180:8080"
      depends_on:
        - idp_mysql
      networks:
        - kc
      volumes:
        - ./keycloak-jars/keycloakListener.jar:/opt/keycloak/providers/keycloakListener.jar


  networks:
    kc:
      name: kc-network
      driver: bridge
    backend:
      name: back-network
      driver: bridge


