server:
  port: ${PORT:8090}
  servlet:
    context-path: /api

keycloak:
  host: ${KEYCLOAK_URL:https://keycloak.victoriousocean-73fa80ad.northeurope.azurecontainerapps.io}
  realm: bandit-realm
  client:
    id: bandit-backend
    secret: ${KEYCLOAK_CLIENT_SECRET}

spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}

  sql:
    init:
      mode: ${DB_INIT_MODE:always}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_PROD:create-drop}
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5555/bandit_db}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASS:password}

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USER:myuser}
    password: ${RABBITMQ_PASS:mypassword}
    virtual-host: ${RABBITMQ_VHOST:/}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:https://keycloak.victoriousocean-73fa80ad.northeurope.azurecontainerapps.io}/realms/bandit-realm
          jwk-set-uri: ${KEYCLOAK_URL:https://keycloak.victoriousocean-73fa80ad.northeurope.azurecontainerapps.io}/realms/bandit-realm/protocol/openid-connect/certs

contexts:
  gameRegistry:
    baseUrl: ${GAME_REGISTRY_URL:http://localhost:8090/api}
  frontend:
    baseUrl: ${FRONTEND_URL:http://localhost:5173}

stripe:
  apiKey: ${STRIPE_API_KEY}

python:
  url: ${PYTHON_URL:http://localhost:8000}

