server:
  port: ${PORT:8090}
  servlet:
    context-path: /api

keycloak:
  host: http://localhost:8180
  realm: bandit-realm
  client:
    id: bandit-backend
    secret: ${KEYCLOAK_CLIENT_SECRET}

spring:
  config:
    additional-location: ${SPRING_CONFIG_ADDITIONAL_LOCATION}

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      show-sql: true
    defer-datasource-initialization: true

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5555/bandit_db}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASS:password}

  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: mypassword

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/bandit-realm
          jwk-set-uri: http://localhost:8180/realms/bandit-realm/protocol/openid-connect/certs

contexts:
  gameRegistry:
    baseUrl: http://localhost:8090/api
  frontend:
    baseUrl: http://localhost:5173

stripe:
  apiKey: ${STRIPE_API_KEY}
